allowBuilds:
  core-js: set this to true or false
  core-js-pure: set this to true or false
  typesense-instantsearch-adapter: set this to true or false
ignoredBuiltDependencies:
  - core-js
  - core-js-pure
  - typesense-instantsearch-adapter
strictDepBuilds: false
