name: typesense-scraper

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      TYPESENSE_API_KEY:
        description: "Typesense API Key"
        required: true

jobs:
  update_search_db:
    runs-on: ubuntu-latest
    name: Update search db
    steps:
      - name: Checkout repo 🛎
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Run DocSearch Scraper 🔍
        run: |
          docker run \
            -env TYPESENSE_API_KEY=${{ secrets.TYPESENSE_API_KEY }} \
            -env TYPESENSE_HOST=${{ secrets.TYPESENSE_HOST }} \
            -env TYPESENSE_PORT=443 \
            -env TYPESENSE_PROTOCOL=https \
            --env "CONFIG=$(cat ./.github/workflows/typesense-scraper-config.json | jq -r tostring)" \
            typesense/docsearch-scraper:0.4.0
