name: typesense-scraper

on:
  workflow_dispatch:
  workflow_call:

jobs:
  update_search_db:
    runs-on: ubuntu-latest
    name: Update search db
    steps:
      - name: Checkout repo 🛎
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Run DocSearch Scraper
        uses: celsiusnarhwal/typesense-scraper@v2
        with:
          api-key: ${{ secrets.TYPESENSE_API_KEY }}
          host: https://typesense-acm-website.livelyriver-a58037c6.northcentralus.azurecontainerapps.io
          port: 443
          protocol: https
          config: ./.github/workflows/typesense-scraper-config.json
